import { musicCatalog as coreCatalog } from './catalogCore'
import {
  lineFuggQuickSumBounce,
  lineFuggVectorRush,
  lineFuggBounceTrackIds,
  lineFuggVectorTrackIds,
  LINEFUGG_BOUNCE_BPM,
  LINEFUGG_SHORT_LOOP_BEATS,
  LINEFUGG_VECTOR_BPM,
  LINEFUGG_VECTOR_LOOP_BEATS,
} from './lineFuggShortLoops'

export const musicCatalog = {
  ...coreCatalog,
  version: 13,
  compositions: [
    ...coreCatalog.compositions,
    {
      id: 'MF-MUS-0008',
      gameId: 'linefugg',
      gameTitle: 'LineFugg',
      name: 'Vector Rush — Three Lines',
      status: 'selected',
      createdAt: '2026-09-06',
      summary: 'Version longue de 48 mesures (~1 min 16) qui conserve exactement les cinq pistes et l’énergie du Vector Rush approuvé. Les variations viennent uniquement des retraits/reprises de kick et clap, de micro-variantes de basse et de petits jeux du trait ascendant.',
      concept: ['three-line board', 'precise electro grid', 'fast cursor hats', '76-second long-form loop', 'rhythmic drop-and-return', 'geometric tension'],
      key: 'E minor',
      meter: '4/4',
      loopBeats: LINEFUGG_VECTOR_LOOP_BEATS,
      midiExports: ['MF-MUS-0008_VectorRush_ThreeLines.mid'],
      stages: [{ label: 'VECTOR', bpm: LINEFUGG_VECTOR_BPM, variant: 'A', activeTracks: [...lineFuggVectorTrackIds] }],
      variants: { A: lineFuggVectorRush() },
    },
    {
      id: 'MF-MUS-0009',
      gameId: 'linefugg',
      gameTitle: 'LineFugg',
      name: 'Quick Sum Bounce',
      status: 'selected',
      createdAt: '2026-09-06',
      summary: 'Alternative joueuse réduite à son meilleur noyau : kick rond, rim-clap, ticks de contretemps et basse rebondissante sur Am–F–C–G / Am–F–Dm–E. Les deux voix mélodiques rejetées ont été retirées du mix canonique.',
      concept: ['quick mental calculation', 'syncopated four-track groove', 'percussion and bass only', 'playful not childish', 'short-session loop'],
      key: 'A minor',
      meter: '4/4',
      loopBeats: LINEFUGG_SHORT_LOOP_BEATS,
      midiExports: ['MF-MUS-0009_QuickSumBounce.mid'],
      stages: [{ label: 'BOUNCE', bpm: LINEFUGG_BOUNCE_BPM, variant: 'A', activeTracks: [...lineFuggBounceTrackIds] }],
      variants: { A: lineFuggQuickSumBounce() },
    },
  ],
} as const
