import { musicCatalog as coreCatalog } from './catalogCore'
import {
  lineFuggQuickSumBounce,
  lineFuggVectorRush,
  lineFuggBounceTrackIds,
  lineFuggVectorTrackIds,
  LINEFUGG_BOUNCE_BPM,
  LINEFUGG_SHORT_LOOP_BEATS,
  LINEFUGG_VECTOR_BPM,
} from './lineFuggShortLoops'

export const musicCatalog = {
  ...coreCatalog,
  version: 10,
  compositions: [
    ...coreCatalog.compositions,
    {
      id: 'MF-MUS-0008',
      gameId: 'linefugg',
      gameTitle: 'LineFugg',
      name: 'Vector Rush — Three Lines',
      status: 'selected',
      createdAt: '2026-09-06',
      summary: 'Boucle courte et sèche pour tracer vite : kick net, caisse claire vectorielle, curseur en doubles croches, basse syncopée et petit trait ascendant. L’ancienne impulsion aiguë trois lignes a été retirée du mix canonique.',
      concept: ['three-line board', 'precise electro grid', 'fast cursor hats', 'short-session loop', 'geometric tension'],
      key: 'E minor',
      meter: '4/4',
      loopBeats: LINEFUGG_SHORT_LOOP_BEATS,
      midiExports: ['MF-MUS-0008_VectorRush_ThreeLines.mid'],
      stages: [{ label: 'VECTOR', bpm: LINEFUGG_VECTOR_BPM, variant: 'A', activeTracks: [...lineFuggVectorTrackIds] }],
      variants: { A: lineFuggVectorRush() },
    },
    {
      id: 'MF-MUS-0009',
      gameId: 'linefugg',
      gameTitle: 'LineFugg',
      name: 'Quick Sum Bounce',
      status: 'candidate',
      createdAt: '2026-09-06',
      summary: 'Alternative joueuse réécrite autour d’une progression Am–F–C–G / Am–F–Dm–E : le kick, le rim-clap et la basse rebondissante restent, tandis qu’une question et une réponse mélodiques alternent sans superposition ni notes étrangères aux accords.',
      concept: ['quick mental calculation', 'syncopated bounce', 'two-bar call and response', 'playful not childish', 'short-session loop'],
      key: 'A minor',
      meter: '4/4',
      loopBeats: LINEFUGG_SHORT_LOOP_BEATS,
      midiExports: ['MF-MUS-0009_QuickSumBounce.mid'],
      stages: [{ label: 'BOUNCE', bpm: LINEFUGG_BOUNCE_BPM, variant: 'A', activeTracks: [...lineFuggBounceTrackIds] }],
      variants: { A: lineFuggQuickSumBounce() },
    },
  ],
} as const
