import type { InstagameDefinition } from './types'
import { LineFugg } from '../games/linefugg/LineFugg'
import { ShootTheShooter } from '../games/shoot-the-shooter/ShootTheShooter'
import { VladsSkewers } from '../games/vlads-skewers/VladsSkewers'
import { HariRottenTeeth } from '../games/hari-rotten-teeth/HariRottenTeeth'
import { CalcDrop } from '../games/calc-drop/CalcDrop'
import { CrazyPapers } from '../games/crazy-papers/CrazyPapers'
import { DebthOfLife } from '../games/debth-of-life/DebthOfLife'

export const gameRegistry: InstagameDefinition[] = [
  {
    id: 'linefugg',
    title: 'LineFugg',
    description: '3 traits · fais le plus gros score',
    author: 'MiniFugg',
    orientation: 'portrait',
    component: LineFugg,
    instructions: {
      goal: 'Trace 3 lignes et fabrique le plus gros score possible.',
      rules: [
        'Chaque ligne peut faire jusqu’à 5 cases, en horizontal, vertical ou diagonal.',
        'Le calcul se fait dans le sens de la flèche.',
        'Deux lignes peuvent se croiser sur une seule case.',
        'Ton score final est la somme de tes 3 lignes.',
      ],
      controls: ['Glisse pour tracer une ligne', 'Relâche pour valider', 'Annule avant le 3e trait'],
    },
    features: {
      help: true,
      love: true,
      comments: true,
      bookmark: true,
      leaderboard: {
        enabled: true,
        periods: ['daily', 'weekly'],
        sort: 'desc',
        limit: 10,
      },
      share: false,
      remix: false,
    },
  },
  {
    id: 'shoot-the-shooter',
    title: 'Shoot the Shooter',
    description: 'Bois, mémorise, tiens jusqu’au blackout',
    author: 'MiniFugg',
    orientation: 'landscape',
    component: ShootTheShooter,
    instructions: {
      goal: 'Bois un maximum de shooters sans finir à 100% d’alcool ni rater 3 verres.',
      rules: [
        'Les effets des shooters sont cachés jusqu’à ce que tu les goûtes.',
        'Tape quand le verre que tu veux boire passe sur la cible.',
        'Certains shooters font très mal, d’autres peuvent te dégriser.',
        '3 verres ratés ou 100% d’alcool : partie terminée.',
        'Si tu arrêtes de boire trop longtemps, c’est Last Call.',
      ],
      controls: ['Tape au bon moment', 'Clavier : Espace ou Entrée'],
    },
    features: {
      help: true,
      love: true,
      comments: true,
      bookmark: true,
      leaderboard: {
        enabled: true,
        periods: ['daily', 'weekly'],
        sort: 'desc',
        limit: 10,
      },
      share: false,
      remix: false,
    },
  },
  {
    id: 'vlads-skewers',
    title: 'Les Brochettes de Vlad',
    description: 'Empale la commande · évite l’ail',
    author: 'MiniFugg',
    orientation: 'portrait',
    component: VladsSkewers,
    instructions: {
      goal: 'Prépare les brochettes demandées et sers le plus de clients possible.',
      rules: [
        'Empale les ingrédients dans l’ordre exact de la commande.',
        'Quand la brochette est complète, apporte-la au client.',
        'Un mauvais ingrédient ou de l’ail fait perdre le client.',
        'Le sang redonne de la patience et ralentit temporairement la chute.',
        'Au 3e client perdu, le service est terminé.',
      ],
      controls: ['Maintiens et glisse pour déplacer la brochette', 'Empale avec la pointe', 'Brochette complète : va jusqu’au client'],
    },
    features: {
      help: true,
      love: true,
      comments: true,
      bookmark: true,
      leaderboard: {
        enabled: true,
        periods: ['daily', 'weekly'],
        sort: 'desc',
        limit: 10,
      },
      share: false,
      remix: false,
    },
  },
  {
    id: 'hari-rotten-teeth',
    title: 'HARI les dents pourries',
    description: 'Aligne les bonbons · pourris toute la mâchoire',
    author: 'MiniFugg',
    orientation: 'portrait',
    component: HariRottenTeeth,
    instructions: {
      goal: 'Aligne les bonbons pour pourrir toutes les dents de HARI.',
      rules: [
        'Les pièces contiennent 3 bonbons.',
        'Aligne au moins 3 bonbons identiques, dans n’importe quelle direction.',
        'Les bonbons détruits abîment les dents correspondantes.',
        'Pourris les 8 dents pour passer au niveau suivant.',
        'Si les bonbons atteignent le haut de la grille, la partie est terminée.',
      ],
      controls: ['← → déplacer', '↓ accélérer', '↔ changer l’orientation', '↻ changer l’ordre des bonbons'],
    },
    features: {
      help: true,
      love: true,
      comments: true,
      bookmark: true,
      leaderboard: {
        enabled: true,
        periods: ['daily', 'weekly'],
        sort: 'desc',
        limit: 10,
      },
      share: false,
      remix: false,
    },
  },
  {
    id: 'calc-drop',
    title: 'Calc Drop',
    description: 'Complète des lignes · fabrique des calculs monstrueux',
    author: 'MiniFugg',
    orientation: 'portrait',
    component: CalcDrop,
    instructions: {
      goal: 'Complète des lignes et construis les calculs les plus rentables possible.',
      rules: [
        'Complète une ligne horizontale pour la calculer et la faire disparaître.',
        'Le calcul se lit de gauche à droite : les chiffres s’ajoutent, les × et ÷ modifient le total.',
        '⇄ inverse le sens du calcul. Effacer plusieurs lignes d’un coup peut créer des bonus plus puissants.',
        'Atteins l’objectif de points pour passer au niveau suivant ; la chute accélère à chaque niveau.',
        'Si les pièces atteignent le haut de la grille, la partie est terminée.',
      ],
      controls: ['← → déplacer', '↓ accélérer la chute', '↺ ↻ tourner', 'Clavier : flèches, Z et X'],
    },
    features: {
      help: true,
      love: true,
      comments: true,
      bookmark: true,
      leaderboard: {
        enabled: true,
        periods: ['daily', 'weekly'],
        sort: 'desc',
        limit: 10,
      },
      share: false,
      remix: false,
    },
  },
  {
    id: 'crazy-papers',
    title: 'CrazyPapers',
    description: 'Lis les indices · trie les dossiers · ne noie pas le bureau',
    author: 'MiniFugg',
    orientation: 'portrait',
    component: CrazyPapers,
    instructions: {
      goal: 'Envoie un maximum de documents au bon secteur avant que les piles envahissent le bureau.',
      rules: [
        'Trois secteurs existent : COMPTABILITÉ, ÉTAT CIVIL et URBANISME.',
        'Chaque secteur possède quatre familles de documents récurrentes à apprendre.',
        'Un document peut être reconnu par son intitulé, sa couleur, sa mise en page, son contenu ou son symbole.',
        'Au début les cinq indices sont visibles, puis le jeu en retire progressivement jusqu’à ne laisser qu’un seul indice exploitable.',
        'Un mauvais secteur fait revenir le dossier de la gauche avec un cachet rouge et ajoute du travail pendant que le supérieur t’engueule.',
        'Quand les piles atteignent la limite du bureau, la partie se termine.',
      ],
      controls: ['Tape sur COMPTABILITÉ, ÉTAT CIVIL ou URBANISME', 'Clavier : 1 = COMPTA · 2 = ÉTAT CIVIL · 3 = URBANISME'],
    },
    features: {
      help: true,
      love: true,
      comments: true,
      bookmark: true,
      leaderboard: {
        enabled: true,
        periods: ['daily', 'weekly'],
        sort: 'desc',
        limit: 10,
      },
      share: false,
      remix: false,
    },
  },
  {
    id: 'debth-of-life',
    title: 'DebthOfLife',
    description: 'Cours ta vie · saute les dettes · meurs le moins pauvre possible',
    author: 'MiniFugg',
    orientation: 'landscape',
    component: DebthOfLife,
    instructions: {
      goal: 'Atteins 85 ans avec le meilleur patrimoine net possible.',
      rules: [
        'Tu cours automatiquement : ton seul pouvoir est de sauter.',
        'Maintiens le saut pour monter plus haut. En vieillissant, tu cours moins vite et sautes moins haut.',
        'Voiture, couple, enfant, chien, maison, crédit, impôts et maladie coûtent de l’argent et peuvent ajouter de la dette.',
        'Certains coûts te laissent aussi un acquis qui compte dans ton bilan final.',
        'Prime, meilleur métier, augmentation, promotion, héritage et loterie donnent de l’argent ou améliorent ton salaire.',
        'Une partie de ce que tu gagnes rembourse automatiquement tes dettes. Plus elles pèsent lourd, plus le monde s’assombrit.',
      ],
      controls: ['Maintiens SAUTE pour régler la hauteur', 'Clavier : Espace, ↑, W ou Z'],
    },
    features: {
      help: true,
      love: true,
      comments: true,
      bookmark: true,
      leaderboard: {
        enabled: true,
        periods: ['daily', 'weekly'],
        sort: 'desc',
        limit: 10,
      },
      share: false,
      remix: false,
    },
  },
]
