import type { InstagameDefinition } from './types'
import { LineFugg } from '../games/linefugg/LineFugg'
import { ShootTheShooter } from '../games/shoot-the-shooter/ShootTheShooter'
import { VladsSkewers } from '../games/vlads-skewers/VladsSkewers'
import { HariRottenTeeth } from '../games/hari-rotten-teeth/HariRottenTeeth'
import { CalcDrop } from '../games/calc-drop/CalcDrop'
import { CrazyPapers } from '../games/crazy-papers/CrazyPapers'
import { DebthOfLife } from '../games/debth-of-life/DebthOfLife'
import { TrainFighter } from '../games/train-fighter/TrainFighter'

export const gameRegistry: InstagameDefinition[] = [
  {
    id: 'train-fighter',
    title: 'Train Fighter',
    description: 'Change de voie · équipe ton train · choisis tes bastons',
    author: 'MiniFugg',
    orientation: 'portrait',
    component: TrainFighter,
    instructions: {
      goal: 'Traverse les 4 mondes avec le plus de wagons possible et transforme ta petite loco en machine à baffes.',
      rules: [
        'Ton train avance tout seul : LEFT et RIGHT servent uniquement à changer de voie.',
        'Les wagons derrière ta locomotive sont ta vie. Un combat trop difficile peut en décrocher plusieurs.',
        'Percute les pièces, armes, wagons, boucliers et turbos que tu veux récupérer.',
        'Les trains ennemis se battent automatiquement si tu restes sur leur voie. Une meilleure arme et l’armure réduisent les dégâts.',
        'Entre les mondes, la station te permet de dépenser tes pièces en wagon, arme ou armure.',
        'Traverse Mossy Forest, Red Canyon, Cloud Mountain puis Aurora Pass pour terminer la partie.',
      ],
      controls: ['LEFT / RIGHT pour changer de voie', 'Clavier : ← →, A/D ou Q/D'],
    },
    features: {
      help: true,
      love: true,
      comments: true,
      bookmark: true,
      leaderboard: {
        enabled: true,
        periods: ['daily', 'weekly'],
        sort: 'desc',
        limit: 10,
      },
      share: false,
      remix: false,
    },
  },
  {
    id: 'linefugg',
    title: 'LineFugg',
    description: '3 traits · fais le plus gros score',
    author: 'MiniFugg',
    orientation: 'portrait',
    component: LineFugg,
    instructions: {
      goal: 'Trace 3 lignes et fabrique le plus gros score possible.',
      rules: [
        'Chaque ligne peut faire jusqu’à 5 cases, en horizontal, vertical ou diagonal.',
        'Le calcul se fait dans le sens de la flèche.',
        'Deux lignes peuvent se croiser sur une seule case.',
        'Ton score final est la somme de tes 3 lignes.',
      ],
      controls: ['Glisse pour tracer une ligne', 'Relâche pour valider', 'Annule avant le 3e trait'],
    },
    features: {
      help: true,
      love: true,
      comments: true,
      bookmark: true,
      leaderboard: {
        enabled: true,
        periods: ['daily', 'weekly'],
        sort: 'desc',
        limit: 10,
      },
      share: false,
      remix: false,
    },
  },
  {
    id: 'shoot-the-shooter',
    title: 'Shoot the Shooter',
    description: 'Bois, mémorise, tiens jusqu’au blackout',
    author: 'MiniFugg',
    orientation: 'landscape',
    component: ShootTheShooter,
    instructions: {
      goal: 'Bois un maximum de shooters sans finir à 100% d’alcool ni rater 3 verres.',
      rules: [
        'Les effets des shooters sont cachés jusqu’à ce que tu les goûtes.',
        'Tape quand le verre que tu veux boire passe sur la cible.',
        'Certains shooters font très mal, d’autres peuvent te dégriser.',
        '3 verres ratés ou 100% d’alcool : partie terminée.',
        'Si tu arrêtes de boire trop longtemps, c’est Last Call.',
      ],
      controls: ['Tape au bon moment', 'Clavier : Espace ou Entrée'],
    },
    features: {
      help: true,
      love: true,
      comments: true,
      bookmark: true,
      leaderboard: {
        enabled: true,
        periods: ['daily', 'weekly'],
        sort: 'desc',
        limit: 10,
      },
      share: false,
      remix: false,
    },
  },
  {
    id: 'vlads-skewers',
    title: 'Les Brochettes de Vlad',
    description: 'Empale la commande · évite l’ail',
    author: 'MiniFugg',
    orientation: 'portrait',
    component: VladsSkewers,
    instructions: {
      goal: 'Prépare les brochettes demandées et sers le plus de clients possible.',
      rules: [
        'Empale les ingrédients dans l’ordre exact de la commande.',
        'Quand la brochette est complète, apporte-la au client.',
        'Un mauvais ingrédient ou de l’ail fait perdre le client.',
        'Le sang redonne de la patience et ralentit temporairement la chute.',
        'Au 3e client perdu, le service est terminé.',
      ],
      controls: ['Maintiens et glisse pour déplacer la brochette', 'Empale avec la pointe', 'Brochette complète : va jusqu’au client'],
    },
    features: {
      help: true,
      love: true,
      comments: true,
      bookmark: true,
      leaderboard: {
        enabled: true,
        periods: ['daily', 'weekly'],
        sort: 'desc',
        limit: 10,
      },
      share: false,
      remix: false,
    },
  },
  {
    id: 'hari-rotten-teeth',
    title: 'HARI les dents pourries',
    description: 'Aligne les bonbons · pourris toute la mâchoire',
    author: 'MiniFugg',
    orientation: 'portrait',
    component: HariRottenTeeth,
    instructions: {
      goal: 'Aligne les bonbons pour pourrir toutes les dents de HARI.',
      rules: [
        'Les pièces contiennent 3 bonbons.',
        'Aligne au moins 3 bonbons identiques, dans n’importe quelle direction.',
        'Les bonbons détruits abîment les dents correspondantes.',
        'Pourris les 8 dents pour passer au niveau suivant.',
        'Si les bonbons atteignent le haut de la grille, la partie est terminée.',
      ],
      controls: ['← → déplacer', '↓ accélérer', '↔ changer l’orientation', '↻ changer l’ordre des bonbons'],
    },
    features: {
      help: true,
      love: true,
      comments: true,
      bookmark: true,
      leaderboard: {
        enabled: true,
        periods: ['daily', 'weekly'],
        sort: 'desc',
        limit: 10,
      },
      share: false,
      remix: false,
    },
  },
  {
    id: 'calc-drop',
    title: 'Calc Drop',
    description: 'Complète des lignes · fabrique des calculs monstrueux',
    author: 'MiniFugg',
    orientation: 'portrait',
    component: CalcDrop,
    instructions: {
      goal: 'Complète des lignes et construis les calculs les plus rentables possible.',
      rules: [
        'Complète une ligne horizontale pour la calculer et la faire disparaître.',
        'Le calcul se lit de gauche à droite : les chiffres s’ajoutent, les × et ÷ modifient le total.',
        '⇄ inverse le sens du calcul. Effacer plusieurs lignes d’un coup peut créer des bonus plus puissants.',
        'Atteins l’objectif de points pour passer au niveau suivant ; la chute accélère à chaque niveau.',
        'Si les pièces atteignent le haut de la grille, la partie est terminée.',
      ],
      controls: ['← → déplacer', '↓ accélérer la chute', '↺ ↻ tourner', 'Clavier : flèches, Z et X'],
    },
    features: {
      help: true,
      love: true,
      comments: true,
      bookmark: true,
      leaderboard: {
        enabled: true,
        periods: ['daily', 'weekly'],
        sort: 'desc',
        limit: 10,
      },
      share: false,
      remix: false,
    },
  },
  {
    id: 'crazy-papers',
    title: 'CrazyPapers',
    description: 'Monte en grade · trie 5 services · survis aux liasses',
    author: 'MiniFugg',
    orientation: 'portrait',
    component: CrazyPapers,
    instructions: {
      goal: 'Épuise chaque charge de travail, monte en grade et traite un maximum de documents avant que les piles envahissent le bureau.',
      rules: [
        'Cinq services existent : COMPTABILITÉ, ÉTAT CIVIL, URBANISME, RESSOURCES HUMAINES et AFFAIRES JURIDIQUES.',
        'Chaque service possède quatre familles de documents qui se débloquent progressivement.',
        'Un document peut être reconnu par son intitulé, sa couleur, sa mise en page, son contenu ou son symbole ; il garde toujours au moins un indice utile.',
        'Quand toute la charge d’un niveau est réellement épuisée, tu es promu : la pile suivante est plus grosse, le courrier arrive plus vite et les indices diminuent.',
        'Des événements peuvent ajouter une liasse, faire passer un dossier urgent devant les autres ou dupliquer un dossier avec la photocopieuse folle.',
        'Un mauvais service fait revenir le dossier de la gauche avec un cachet rouge et ajoute du travail pendant que le supérieur t’engueule.',
        'À 24 dossiers en attente, le bureau est submergé et la partie se termine.',
      ],
      controls: ['Tape sur l’un des 5 tampons de service', 'Clavier : 1 COMPTA · 2 CIVIL · 3 URBA · 4 RH · 5 JURIDIQUE'],
    },
    features: {
      help: true,
      love: true,
      comments: true,
      bookmark: true,
      leaderboard: {
        enabled: true,
        periods: ['daily', 'weekly'],
        sort: 'desc',
        limit: 10,
      },
      share: false,
      remix: false,
    },
  },
  {
    id: 'debth-of-life',
    title: 'DebthOfLife',
    description: 'Cours ta vie · signe tes choix en sautant · meurs avec le meilleur bilan',
    author: 'MiniFugg',
    orientation: 'landscape',
    component: DebthOfLife,
    instructions: {
      goal: 'Atteins 85 ans avec le meilleur patrimoine net possible.',
      rules: [
        'Tu cours automatiquement et tu ne peux que sauter.',
        'Chaque grand panneau propose deux choix de vie : rester au sol signe le contrat du bas, sauter signe celui du haut.',
        'Aucun choix n’est simplement bon ou mauvais : dette, salaire, cash et actifs peuvent évoluer en même temps.',
        'Les factures dans la route coûtent de l’argent ; les pièces en euros génèrent du revenu et remboursent automatiquement une partie de la dette.',
        'Plus tu vieillis, moins tu cours vite et moins tu sautes haut : certains choix deviennent mécaniquement plus difficiles à atteindre.',
        'Plus la dette pèse lourd, plus la zone rouge te rattrape depuis la gauche. Le score final est banque + actifs − dette.',
      ],
      controls: ['Maintiens SAUTER pour viser le contrat du haut', 'Relâche tôt pour rester plus bas', 'Clavier : Espace, ↑, W ou Z'],
    },
    features: {
      help: true,
      love: true,
      comments: true,
      bookmark: true,
      leaderboard: {
        enabled: true,
        periods: ['daily', 'weekly'],
        sort: 'desc',
        limit: 10,
      },
      share: false,
      remix: false,
    },
  },
]
