from pathlib import Path

p = Path('src/core/ProductionLab.tsx')
s = p.read_text()

def rep(old, new, count=1):
    global s
    if old not in s:
        raise SystemExit(f'Missing pattern:\n{old[:240]}')
    s = s.replace(old, new, count)

rep("  linkOverrides: Record<string, SemanticLink[]>\n  nodePositionOverrides: Record<string, Point>", "  linkOverrides: Record<string, SemanticLink[]>\n  canonicalLinkSourceOverrides: Record<string, LinkEndpoint>\n  nodePositionOverrides: Record<string, Point>")
rep("    annotations: [], reviewNodes: [], reviewLinks: [], comments: {}, referenceAdjustments: {}, linkOverrides: {},\n    nodePositionOverrides: {}, deletionRequests: {}, screenImages: {},", "    annotations: [], reviewNodes: [], reviewLinks: [], comments: {}, referenceAdjustments: {}, linkOverrides: {},\n    canonicalLinkSourceOverrides: {}, nodePositionOverrides: {}, deletionRequests: {}, screenImages: {},")
rep("      linkOverrides: raw.linkOverrides ?? {},\n      nodePositionOverrides: raw.nodePositionOverrides ?? {},", "      linkOverrides: raw.linkOverrides ?? {},\n      canonicalLinkSourceOverrides: raw.canonicalLinkSourceOverrides ?? {},\n      nodePositionOverrides: raw.nodePositionOverrides ?? {},")
rep("  const [exported, setExported] = useState(false)", "  const [exported, setExported] = useState(false)\n  const [resetDone, setResetDone] = useState(false)")

needle = "  function linkGeometry(sourceEndpoint: LinkEndpoint, targetEndpoint: LinkEndpoint) {"
insert = "  function magneticPoint(endpoint: LinkEndpoint, toward: Point): Point | null {\n    if (endpoint.kind === 'node') {\n      const rect = nodeBounds(endpoint.nodeId)\n      return rect ? closestPointOnRect(toward, rect) : null\n    }\n    if (endpoint.kind === 'annotation') {\n      const annotation = annotationsById.get(endpoint.annotationId)\n      const rect = annotationBounds(endpoint.annotationId)\n      if (!rect) return null\n      return annotation?.type === 'point' ? rectCenter(rect) : closestPointOnRect(toward, rect)\n    }\n    return endpointCenter(endpoint)\n  }\n\n"
rep(needle, insert + needle)

rep("    if (drag.kind === 'canonical' && drag.sourceNodeId) {\n      original = effectiveCanonicalLinks(drag.sourceNodeId).find((link) => link.id === drag.linkId)?.target ?? null\n    } else {", "    if (drag.kind === 'canonical' && drag.sourceNodeId) {\n      const key = `${drag.sourceNodeId}:${drag.linkId}`\n      const link = effectiveCanonicalLinks(drag.sourceNodeId).find((item) => item.id === drag.linkId)\n      original = drag.side === 'source'\n        ? reviewRef.current.canonicalLinkSourceOverrides[key] ?? { kind: 'node', nodeId: drag.sourceNodeId }\n        : link?.target ?? null\n    } else {")

rep("    if (drag.snapped) {\n      const center = endpointCenter(drag.snapped)\n      if (center && distance(world, center) <= SNAP_OUT_PX / camera.zoom) {\n        setLinkGhost(visualEndpoint(drag.snapped, world) ?? center)\n        return\n      }\n      drag.snapped = null\n    }", "    if (drag.snapped) {\n      const snapPoint = magneticPoint(drag.snapped, world)\n      if (snapPoint && distance(world, snapPoint) <= SNAP_OUT_PX / camera.zoom) {\n        setLinkGhost(snapPoint)\n        return\n      }\n      drag.snapped = null\n    }")

rep("    if (drag.kind === 'canonical' && drag.sourceNodeId) {\n      commitReview((current) => {\n        const base = current.linkOverrides[drag.sourceNodeId!] ?? canonicalNodesById.get(drag.sourceNodeId!)?.links ?? []\n        return { ...current, linkOverrides: { ...current.linkOverrides, [drag.sourceNodeId!]: base.map((link) => link.id === drag.linkId ? { ...link, target: endpoint } : link) } }\n      })\n    } else {", "    if (drag.kind === 'canonical' && drag.sourceNodeId) {\n      if (drag.side === 'source') {\n        const key = `${drag.sourceNodeId}:${drag.linkId}`\n        commitReview((current) => ({ ...current, canonicalLinkSourceOverrides: { ...current.canonicalLinkSourceOverrides, [key]: endpoint } }))\n      } else {\n        commitReview((current) => {\n          const base = current.linkOverrides[drag.sourceNodeId!] ?? canonicalNodesById.get(drag.sourceNodeId!)?.links ?? []\n          return { ...current, linkOverrides: { ...current.linkOverrides, [drag.sourceNodeId!]: base.map((link) => link.id === drag.linkId ? { ...link, target: endpoint } : link) } }\n        })\n      }\n    } else {")

rep("  function resetLocalReview() {\n    if (!window.confirm('Revenir au Plan canonique et supprimer toutes les modifications locales de ce jeu ?')) return\n    try { localStorage.removeItem(`mf-production-review:${game.id}`) } catch { /* no-op */ }\n    const next = emptyReview()\n    assignReview(next)\n    undoRef.current = []\n    redoRef.current = []\n    setSelection(null)\n    setTool(null)\n    setLinkDraft(null)\n    setReferenceEditing(false)\n  }", "  function resetLocalReview() {\n    if (!window.confirm('Revenir exactement au Plan canonique initial et supprimer toutes les modifications locales de ce jeu ?')) return\n    const next = emptyReview()\n    try { localStorage.setItem(`mf-production-review:${game.id}`, JSON.stringify(next)) } catch { /* no-op */ }\n    assignReview(next)\n    undoRef.current = []\n    redoRef.current = []\n    panRef.current = null\n    pinchRef.current = null\n    nodeDragRef.current = null\n    annotationDragRef.current = null\n    endpointDragRef.current = null\n    touchesRef.current.clear()\n    setSelection(null)\n    setTool(null)\n    setLinkDraft(null)\n    setLinkGhost(null)\n    setGesture(null)\n    setReferenceEditing(false)\n    setReference('minimum')\n    setViewMode('exploded')\n    setCollapsedScreens(new Set())\n    setCamera({ x: 22, y: 36, zoom: 0.34 })\n    setExported(false)\n    setResetDone(true)\n    window.setTimeout(() => setResetDone(false), 1400)\n  }")

rep("      referenceAdjustments: review.referenceAdjustments, linkOverrides: review.linkOverrides,\n      nodePositionOverrides: review.nodePositionOverrides, deletionRequests: Object.values(review.deletionRequests),", "      referenceAdjustments: review.referenceAdjustments, linkOverrides: review.linkOverrides,\n      canonicalLinkSourceOverrides: review.canonicalLinkSourceOverrides,\n      nodePositionOverrides: review.nodePositionOverrides, deletionRequests: Object.values(review.deletionRequests),")

rep("            {renderedCanonicalNodes.flatMap((node) => {\n              const sourceEndpoint: LinkEndpoint = { kind: 'node', nodeId: node.id }\n              return effectiveCanonicalLinks(node.id).map((link) => {\n                const drag = endpointDragRef.current\n                const geometry = linkGeometry(sourceEndpoint, link.target)", "            {renderedCanonicalNodes.flatMap((node) => {\n              return effectiveCanonicalLinks(node.id).map((link) => {\n                const drag = endpointDragRef.current\n                const sourceEndpoint: LinkEndpoint = review.canonicalLinkSourceOverrides[`${node.id}:${link.id}`] ?? { kind: 'node', nodeId: node.id }\n                const geometry = linkGeometry(sourceEndpoint, link.target)")

rep("                const source = geometry.source\n                let target = geometry.target\n                if (drag?.kind === 'canonical' && drag.sourceNodeId === node.id && drag.linkId === link.id && linkGhost) target = linkGhost", "                let source = geometry.source\n                let target = geometry.target\n                if (drag?.kind === 'canonical' && drag.sourceNodeId === node.id && drag.linkId === link.id && linkGhost) {\n                  if (drag.side === 'source') source = linkGhost\n                  else target = linkGhost\n                }")

rep("                  {selected && <circle className=\"mfpl-link-target-halo\" cx={target.x} cy={target.y} r=\"18\" />}\n                  <circle className=\"mfpl-link-target\" cx={target.x} cy={target.y} r={selected ? 6 : 4} />\n                  {selected && <circle className=\"mfpl-link-handle\" cx={target.x} cy={target.y} r=\"9\" onPointerDown={(event) => startEndpointDrag(event, { kind: 'canonical', linkId: link.id, sourceNodeId: node.id, side: 'target' })} onPointerMove={moveEndpointDrag} onPointerUp={endEndpointDrag} onPointerCancel={endEndpointDrag} />}", "                  {selected && <circle className=\"mfpl-link-target-halo\" cx={target.x} cy={target.y} r=\"18\" />}\n                  <circle className=\"mfpl-link-target\" cx={source.x} cy={source.y} r={selected ? 6 : 4} />\n                  <circle className=\"mfpl-link-target\" cx={target.x} cy={target.y} r={selected ? 6 : 4} />\n                  {selected && <>\n                    <circle className=\"mfpl-link-handle\" cx={source.x} cy={source.y} r=\"9\" onPointerDown={(event) => startEndpointDrag(event, { kind: 'canonical', linkId: link.id, sourceNodeId: node.id, side: 'source' })} onPointerMove={moveEndpointDrag} onPointerUp={endEndpointDrag} onPointerCancel={endEndpointDrag} />\n                    <circle className=\"mfpl-link-handle\" cx={target.x} cy={target.y} r=\"9\" onPointerDown={(event) => startEndpointDrag(event, { kind: 'canonical', linkId: link.id, sourceNodeId: node.id, side: 'target' })} onPointerMove={moveEndpointDrag} onPointerUp={endEndpointDrag} onPointerCancel={endEndpointDrag} />\n                  </>}")

rep("                <line className=\"mfpl-link-hit\" x1={source.x} y1={source.y} x2={target.x} y2={target.y} onClick={(event) => { event.stopPropagation(); setSelection({ kind: 'review-link', id: link.id }) }} />\n                {selected && <>", "                <line className=\"mfpl-link-hit\" x1={source.x} y1={source.y} x2={target.x} y2={target.y} onClick={(event) => { event.stopPropagation(); setSelection({ kind: 'review-link', id: link.id }) }} />\n                <circle className=\"mfpl-link-target\" cx={source.x} cy={source.y} r={selected ? 6 : 4} />\n                <circle className=\"mfpl-link-target\" cx={target.x} cy={target.y} r={selected ? 6 : 4} />\n                {selected && <>")

rep("      <button className=\"mfpl-reset-review\" title=\"Revenir au Plan canonique\" onClick={resetLocalReview}>↺</button>", "      <button className=\"mfpl-reset-review\" title=\"Réinitialiser complètement la revue locale\" onClick={resetLocalReview}>{resetDone ? '✓' : '↺'}</button>")

rep("<div className=\"mfpl-link-summary\"><b>{effectiveCanonicalLinks(selectedCanonicalNode.id).length} lien(s)</b><span>Glisse directement une poignée orange pour changer sa destination. Utilise l’outil Lien pour ajouter une relation locale.</span></div>", "<div className=\"mfpl-link-summary\"><b>{effectiveCanonicalLinks(selectedCanonicalNode.id).length} lien(s)</b><span>Tous les liens canoniques utilisent les mêmes poignées : clique le nœud puis glisse l’extrémité de départ ou d’arrivée directement sur une autre cible.</span></div>")

p.write_text(s)

d = Path('docs/PRODUCTION_LAB_V1.md')
t = d.read_text()
marker = "## Non-objectifs"
addition = """## Édition uniforme des liens et reset\n\nLes liens canoniques et locaux ont le même comportement visuel de revue : leurs points d’accroche se placent sur la bordure des nœuds, zones et dessins ; sélectionner un nœud révèle les poignées de tous ses liens. Les deux extrémités peuvent être déplacées localement. Le magnétisme utilise deux seuils distincts : accroche à proximité, puis décrochage seulement après un déplacement plus franc.\n\nLe reset de revue restaure l’état initial complet du Lab pour le jeu courant : aucun nœud/repère/lien local, aucun déplacement ou remplacement d’image, aucun override de lien/calage, vue éclatée, repère minimum, écrans non repliés et caméra initiale. Il réécrit explicitement l’état local vide afin qu’un rechargement conserve bien ce retour au canon.\n\n"""
if marker not in t:
    raise SystemExit('docs marker missing')
t = t.replace(marker, addition + marker, 1)
d.write_text(t)
